language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/psalm --config=psalm.xml
  - ./vendor/bin/phpunit --configuration ./phpunit.xml
